-- Generated by tools/make_pose_variants.py: the corrected wheel pose
-- (Animations/xbase_anim.1st/xWheelPoseFix<n>.kf) for each idle that turns the chest away.
-- Idles not listed take the plain pose.
return {
    idle1s = 'fix1',
    idle1ssneak = 'fix1',
    idle1t = 'fix2',
    idle1tsneak = 'fix2',
    idle1tstar = 'fix2',
    idle1tstarsneak = 'fix2',
    idle2w = 'fix1',
    idle2wsneak = 'fix1',
    idlebowsneak = 'fix4',
    idlecrossbow = 'fix3',
    idlecrossbowsneak = 'fix3',
}
